#SETTINGS

#Display Settings
WIDTH = 2440
HEIGHT = 1200
COLORS = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0)]  # Red, Green, Blue, Yellow
SIZE_RANGE = (5, 15)  # Min and max size of particles
SHAPES = ['circle', 'square']  # Available shapes

#Evolution settings
MUTATION_RATE = 1
REGENERATION_DELAY = 5000
DIVISION_THRESHOLD = 550 #costs the cell 50 energy to split

#00 - PLANT VARIABLES
PLANTS_NUM = 200
PLANTS_ENERGY = 50
PLANTS_ENERGY_MAX = 50
PLANT_ENERGY_GROWTH = 1
PLANT_GROWTH_THRESHOLD = 20
PLANT_DECAY = 0
#01 - CELL VARIABLES
CELLS_NUM = 80 # Number of particles in the simulation
ENERGY_INITIAL = 500
CELL_ENERGY_MAX = 1000
CELL_ENERGY_DECAY = 0.25
ENERGY_GAIN_FROM_CELL = 200

#02 - PREDATOR VARIABLES
PREDATORS_NUM = 10
PREDATOR_ENERGY_DECAY = 1
PREDATOR_ENERGY_INITAL = 1000
PREDATOR_ENERGY_GAIN = 400

#03 - OMNIVORE
OMNIVORE_NUMBER = 0
OMNIVORE_ENERGY_INITIAL = 0
OMNIVORE_ENERGY_DECAY = 0.5
OMNIVORE_ENERGY_GAIN = 100

#Environment Settings
temp_env = 22





